POSTMAN_COLLECTION_URL="https://api.getpostman.com/collections/$MORPHEUS_POSTMAN_COLLECTION_UID?apikey=$MORPHEUS_POSTMAN_API_KEY"
POSTMAN_ENV_URL="https://api.getpostman.com/environments/$MORPHEUS_POSTMAN_ENV_UID?apikey=$MORPHEUS_POSTMAN_API_KEY"

newman run $POSTMAN_COLLECTION_URL \
    -e "$POSTMAN_ENV_URL"
