name: Postman CLI workflow

on:
  workflow_dispatch:
    inputs:
      postman_env_uid:
        description: 'The unique ID for the Postman environment that will be used during tests'
        required: true
        default: '2505625-bc9f18c1-4489-406c-a43a-0785704c8e3e'
      postman_collection_uid:
        description: 'The unique ID for the Postman collection that will be used during tests'
        required: true
        default: '2505625-89968805-bda3-4dbb-b165-8675d32262c3'
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTMAN_ENV_UID: ${{ github.event.inputs.postman_env_uid }}
      POSTMAN_COLLECTION_UID: ${{ github.event.inputs.postman_collection_uid }}
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Postman CLI
      run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      
    - name: Install other dependencies
      run: npm install -g postman-to-openapi

    - name: Login to Postman
      run: postman login --with-api-key $POSTMAN_API_KEY

    - name: Get collection definition
      run: |
        curl --request GET \
             --url "https://api.getpostman.com/collections/$POSTMAN_COLLECTION_UID" \
             --header "X-Api-Key: $POSTMAN_API_KEY" > collection.json
             
    - name: Convert collection.json to openapi spec
      run: p2o collection.json -f openapi_spec.yaml
    - name: Lint collection openapi spec
      run: postman api lint openapi_spec.yaml

    - name: Run collection tests
      run: postman collection run collection.json -e $POSTMAN_ENV_UID --verbose

